"""
Celery Event Listener Service

Listens to Celery events from RabbitMQ and updates task status in database.
Worker sends events, backend receives and processes them.

Two flavours of events flow through here:

* **Lifecycle events** (``task-started``/``task-succeeded``/``task-failed``/
  ``task-revoked``) — built-in, generated by Celery itself; we update
  the ``tasks`` row in Postgres and produce final-state snapshots.
* **Custom progress/log events** (``task-progress``/``task-log``) — sent
  by the worker via ``self.send_event(...)`` from inside the deploy
  task. They don't change task status; they update lightweight progress
  columns and are forwarded to any open SSE subscriber via the
  in-process ``DeploymentPubSub``.

The custom events carry ``deployment_id`` directly in the payload so the
listener doesn't need a Postgres roundtrip on the hot path.
"""

import ast
import json
import logging
import re
import time
from typing import Any

from celery.events import EventReceiver
from celery.result import AsyncResult
from sqlalchemy.orm import Session

from app.celery_app import celery_app
from app.crud import deployments as crud_deployments
from app.crud import tasks as crud_tasks
from app.database import SessionLocal
from app.models import TaskStatus, TaskType
from app.services import deployment_notifier
from app.services.deployment_pubsub import pubsub
from app.utils.time import utcnow

logger = logging.getLogger(__name__)


def clean_log_line(line: str) -> str:
    """Clean up log line by removing ANSI escape codes and normalizing quotes"""
    # Remove ANSI color codes
    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
    line = ansi_escape.sub('', line)

    # Normalize escaped quotes
    line = line.replace('""', '"')

    return line


def is_verbose_line(line: str) -> bool:
    """Check if line is very verbose (TRACE/DEBUG from tools)"""
    verbose_patterns = [
        r"\[TRACE\]",
        r"\[DEBUG\]",
        r"json.dumps",
        r"plugingetter",
        r"github-getter",
        r"discovering plugins",
        r"BinaryInstallationOptions",
        r"ListInstallationsOptions",
    ]
    return any(re.search(pattern, line, re.IGNORECASE) for pattern in verbose_patterns)


def filter_logs(text: str, max_lines: int = 100) -> str:
    """
    Filter and clean logs for better readability
    - Remove very verbose lines (TRACE/DEBUG)
    - Remove ANSI escape codes
    - Limit to max_lines if too long
    """
    lines = text.split('\n')

    # Filter verbose lines
    filtered = []
    for line in lines:
        if line.strip() and not is_verbose_line(line):
            cleaned = clean_log_line(line)
            if cleaned.strip():
                filtered.append(cleaned)

    # If still too long, keep important parts
    if len(filtered) > max_lines:
        # Keep first 20 lines and last 30 lines
        important = filtered[:20] + ["..."] + filtered[-30:]
        return "\n".join(important)

    return "\n".join(filtered)


def format_logs(logs_data) -> str:
    """Format logs from structured format to readable text"""
    if isinstance(logs_data, list):
        formatted = []
        for entry in logs_data:
            if isinstance(entry, dict):
                timestamp = entry.get("timestamp", "")
                message = entry.get("message", "")
                level = entry.get("level", "INFO")
                icon = _get_icon(level)

                # Clean up message (remove ANSI codes)
                message = clean_log_line(message)

                # For long messages, truncate intelligently
                if len(message) > 500:
                    # If it looks like multiple lines, keep the structure
                    if '\n' in message:
                        lines = message.split('\n')
                        if len(lines) > 20:
                            # Too many lines, filter verbose ones
                            message = filter_logs(message)
                    else:
                        message = message[:500] + "..."

                formatted.append(f"{icon} [{timestamp}] {message}")
            elif isinstance(entry, str):
                formatted.append(clean_log_line(entry))
        return "\n".join(formatted)
    return str(logs_data)


def _get_icon(level: str) -> str:
    """Get the leading ASCII marker for a log level.

    Uses a fixed four-character tag (no emoji) so plain-text log lines
    align cleanly; the frontend renders its own coloured pill per level.
    """
    icons = {
        "DEBUG": "[dbg]",
        "INFO":  "[inf]",
        "SUCCESS": " [ok]",
        "WARNING": "[warn]",
        "ERROR": "[err]",
    }
    return icons.get(level, "    -")


# Mapping from common Celery infrastructure exception class names to
# operator-friendly headlines. Keys are matched as substrings against
# the raw ``event['exception']`` repr. Each headline is paired with a
# stable ``failure_kind`` token for the frontend.
_CELERY_INFRA_EXCEPTIONS: tuple[tuple[str, str, str], ...] = (
    (
        "NotRegistered",
        "Worker hat den Task-Typ nicht erkannt — Backend und Worker sind "
        "nicht synchron. Bitte den Administrator informieren; das Deployment "
        "selbst läuft weiter.",
        "celery_infrastructure",
    ),
    (
        "WorkerLostError",
        "Der Worker-Prozess wurde während der Ausführung beendet. Der Task "
        "wird ggf. automatisch neu gestartet — bitte den Status in Kürze "
        "erneut prüfen.",
        "celery_infrastructure",
    ),
    (
        "TimeoutError",
        "Der Task hat das Zeit-Limit überschritten. Wenn das wiederholt "
        "passiert, ist meist die OpenStack-Region überlastet.",
        "celery_infrastructure",
    ),
    (
        "Reject",
        "Der Worker hat den Task abgelehnt — wahrscheinlich ein "
        "Routing- oder Konfigurationsproblem auf der Plattform.",
        "celery_infrastructure",
    ),
    (
        "ContentDisallowed",
        "Der Task konnte nicht deserialisiert werden. Das ist ein "
        "Plattform-Bug — bitte den Administrator informieren.",
        "celery_infrastructure",
    ),
)


def _translate_celery_infra_exception(
    exception_repr: str,
) -> tuple[str | None, str | None]:
    """Pick a human-readable headline + failure_kind for known Celery
    infrastructure exceptions.

    Returns ``(None, None)`` when ``exception_repr`` matches no known
    class; the caller then falls back to the raw exception text.
    """
    if not exception_repr:
        return (None, None)
    for needle, headline, kind in _CELERY_INFRA_EXCEPTIONS:
        if needle in exception_repr:
            return (headline, kind)
    return (None, None)


def _update_task_progress(deployment_id: str, event: dict) -> None:
    """Persist phase / progress columns for the active deploy task.

    Best-effort: updates two cheap columns on the most recent active
    task. Failures are logged at debug-level — the SSE stream is the
    source of truth; these columns are only the reload fallback.
    """
    db: Session = SessionLocal()
    try:
        tasks = crud_tasks.get_tasks(db, deployment_id=deployment_id)
        # Pick the latest task that is still in flight; created_at
        # ordering matches the listener's own `task-started` write.
        active = next(
            (
                t
                for t in sorted(tasks, key=lambda x: x.created_at, reverse=True)
                if t.status in (TaskStatus.RUNNING, TaskStatus.PENDING)
            ),
            None,
        )
        if active is None:
            return
        update: dict = {}
        phase = event.get('phase')
        pct = event.get('progress_pct')
        if phase is not None:
            update['current_phase'] = phase
        if pct is not None:
            # Clamp defensively — the worker sends 0..100 already.
            update['progress_pct'] = max(0, min(100, int(pct)))
        if update:
            crud_tasks.update_task(db, active.taskId, update)
    except Exception as e:
        logger.debug(f"Could not persist progress for {deployment_id}: {e}")
    finally:
        db.close()


def _handle_custom_event(event: dict) -> None:
    """Fan a live progress/log event out to SSE subscribers.

    These are emitted via ``self.send_event(...)`` from the deploy task
    and carry ``deployment_id`` directly, so they fan out without a DB
    lookup.
    """
    deployment_id = event.get('deployment_id')
    if not deployment_id:
        return
    # Forward to live subscribers first; ephemeral data shouldn't wait
    # for the DB write.
    pubsub.publish(deployment_id, event)

    # For progress events also persist the latest phase / percent so a
    # detail-view reload after a reconnect shows current state.
    if event.get('type') == 'task-progress':
        _update_task_progress(deployment_id, event)


def _handle_task_started(celery_task_id: str) -> dict:
    """Build the update payload for a ``task-started`` lifecycle event."""
    logger.info(f"Task {celery_task_id} started")
    return {
        "status": TaskStatus.RUNNING,
        "started_at": utcnow()
    }


def _handle_task_succeeded(celery_task_id: str) -> tuple[dict, Any]:
    """Build the update payload for a ``task-succeeded`` event.

    Pulls the full result payload from the result backend and
    normalizes logs / tf_state / outputs into the DB column shapes.
    Returns the update dict plus the raw ``outputs`` value so the
    orchestrator can hand it to the deploy notifier without re-fetching.
    """
    logger.info(f"Task {celery_task_id} succeeded")

    # Pull the FULL result payload from the result backend.
    async_result = AsyncResult(celery_task_id, app=celery_app)
    result = async_result.result

    if isinstance(result, dict):
        logs_data = result.get('logs')
        tf_state = result.get('tf_state')
        outputs = result.get('terraform_outputs')
    else:
        logs_data = None
        tf_state = None
        outputs = None

    # ``logs_data`` is either already a string or a list of lines.
    if isinstance(logs_data, list):
        logs_str = json.dumps(logs_data, ensure_ascii=False)
    elif isinstance(logs_data, str):
        logs_str = logs_data
    else:
        logs_str = None

    update_data = {
        "status": TaskStatus.SUCCESS,
        "finished_at": utcnow(),
        "logs": logs_str,
        "tf_state": tf_state if isinstance(tf_state, str) else json.dumps(tf_state) if tf_state else None,
        "outputs": outputs if isinstance(outputs, str) else json.dumps(outputs) if outputs else None,
    }
    return update_data, outputs


# ``Failure('<payload>')`` as the worker renders it: ``Failure.__repr__`` is
# ``Failure({args[0]!r})``, so the argument is a complete Python string literal
# (single- or double-quoted, with backslash escapes). Matching the literal as a
# whole, instead of "up to the first ``')``", keeps a ``')`` inside the payload
# from cutting it short.
_FAILURE_REPR_RE = re.compile(
    r"""Failure\((?P<arg>'(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")\)""",
    re.DOTALL,
)
_FAILURE_BARE_RE = re.compile(r"Failure:\s*(\{.+?\})\s*$", re.DOTALL)


def _parse_structured_failure(exception_type: Any, traceback: str) -> dict | None:
    """Extract the worker's structured ``Failure`` JSON payload, if present.

    The worker raises ``Failure`` whose ``args[0]`` is a JSON payload
    with logs/tf_state/etc. It can surface in two forms:

     1. ``Failure('<json>')``, the ``repr()`` of the exception, in
        ``event['exception']`` or inside the traceback;
     2. ``Failure: {"error": ...}`` in the traceback's final line.

    Searches the exception field first, then the traceback. Returns the
    decoded dict, or ``None`` when no structured payload could be parsed.

    The ``repr()`` form is decoded with ``ast.literal_eval`` — the inverse of
    ``repr`` for a string — so umlauts and escapes come back unchanged. The
    previous ``encode('utf-8').decode('unicode_escape')`` read UTF-8 bytes as
    Latin-1 and turned ``Schlüssel`` into ``SchlÃ¼ssel``.
    """
    for haystack in (str(exception_type or ""), traceback or ""):
        if not haystack:
            continue
        candidates: list[str] = []
        repr_match = _FAILURE_REPR_RE.search(haystack)
        if repr_match:
            try:
                literal = ast.literal_eval(repr_match.group("arg"))
            except (ValueError, SyntaxError):
                literal = None
            if isinstance(literal, str):
                candidates.append(literal)
        bare_match = _FAILURE_BARE_RE.search(haystack)
        if bare_match:
            candidates.append(bare_match.group(1))
        for text in candidates:
            try:
                data = json.loads(text)
            except json.JSONDecodeError:
                continue
            if isinstance(data, dict):
                return data
    return None


def _apply_structured_failure(update_data: dict, failure_data: dict) -> None:
    """Fold the parsed worker ``Failure`` payload into ``update_data``.

    Mutates ``update_data`` in place: normalizes logs, appends the error
    line and optional commit info, and copies tf_state / terraform_outputs.
    """
    # logs
    logs_data = failure_data.get('logs')
    if logs_data is not None:
        update_data['logs'] = json.dumps(logs_data) if isinstance(logs_data, list) else str(logs_data)
    # error
    if 'error' in failure_data:
        current_logs = update_data.get('logs', '') or ''
        update_data['logs'] = current_logs + f"\n\n[err] Error: {failure_data['error']}"
    # tf_state
    if 'tf_state' in failure_data:
        update_data['tf_state'] = failure_data['tf_state']
    # commit_info
    if 'commit_info' in failure_data and failure_data['commit_info']:
        commit = failure_data['commit_info']
        if isinstance(commit, dict):
            commit_str = f"\nCommit: {commit.get('hash', 'N/A')[:8]}"
            commit_str += f"\n   Message: {commit.get('message', 'N/A')}"
            commit_str += f"\n   Author: {commit.get('author', 'N/A')}"
            current_logs = update_data.get('logs', '') or ''
            update_data['logs'] = current_logs + commit_str
    # terraform_outputs
    if 'terraform_outputs' in failure_data:
        tf_outputs = failure_data['terraform_outputs']
        if isinstance(tf_outputs, dict):
            update_data['outputs'] = json.dumps(tf_outputs, indent=2)
        else:
            update_data['outputs'] = str(tf_outputs)


def _apply_infra_failure(
    update_data: dict, exception_type: Any, traceback: str
) -> str | None:
    """Render an infrastructure-level failure into ``update_data['logs']``.

    Used when there's no structured ``Failure(...)`` payload (a
    Celery-side error: unknown task name, worker died, broker timeout).
    Translates common ones into a short operator-friendly headline and
    keeps the raw text after a divider. Returns the classified
    ``failure_kind`` (or ``None``).
    """
    headline, kind = _translate_celery_infra_exception(
        str(exception_type or '')
    )
    raw_block = f"{exception_type}\n{traceback}".strip()
    if headline:
        # Divider so the frontend can split headline from raw details.
        update_data['logs'] = (
            f"{headline}\n\n"
            f"--- Technische Details ---\n{raw_block}"
        )
    else:
        update_data['logs'] = f"Task failed: {raw_block}"
    return kind


def _handle_task_failed(celery_task_id: str, event: dict) -> tuple[dict, str | None]:
    """Build the update payload for a ``task-failed`` event.

    Classifies the failure (structured ``worker_failure`` vs.
    ``celery_infrastructure``) and returns the update dict plus the
    ``failure_kind`` token for the SSE pubsub event.
    """
    logger.info(f"Task {celery_task_id} failed")
    exception_type = event.get('exception', 'Unknown error')
    traceback = event.get('traceback', '')
    update_data = {
        "status": TaskStatus.FAILED,
        "finished_at": utcnow(),
        "logs": None,
        "tf_state": None,
        "outputs": None,
    }
    failure_kind: str | None = None
    try:
        failure_data = _parse_structured_failure(exception_type, traceback)
        if failure_data is not None:
            # Structured worker-side failure (terraform apply, packer
            # build, etc.).
            failure_kind = "worker_failure"
            _apply_structured_failure(update_data, failure_data)
            # Never log ``update_data`` here: it carries ``tf_state`` and
            # ``outputs``, i.e. the passwords of the provisioned machines.
            logger.info("[FAILED] Extracted structured failure data for %s", celery_task_id)
        else:
            raise ValueError("Not structured failure format")
    except Exception as parse_error:
        logger.warning(f"Could not parse structured failure: {parse_error}")
        failure_kind = _apply_infra_failure(update_data, exception_type, traceback)
    logger.info("[FAILED] Task %s marked failed (kind=%s)", celery_task_id, failure_kind)
    return update_data, failure_kind


def _handle_task_revoked(celery_task_id: str) -> dict:
    """Build the update payload for a ``task-revoked`` lifecycle event."""
    logger.info(f"Task {celery_task_id} revoked")
    return {
        "status": TaskStatus.CANCELLED,
        "finished_at": utcnow()
    }


def _auto_soft_delete_on_destroy(db: Session, task) -> None:
    """Soft-delete the deployment after a successful destroy.

    The OpenStack resources are gone, so soft-deleting unifies
    "destroy + remove from UI" into one action while keeping the row
    and its tasks/logs for the audit trail.
    """
    try:
        crud_deployments.soft_delete_deployment(db, task.deploymentId)
        logger.info(
            f"Auto-soft-deleted deployment {task.deploymentId} after successful destroy"
        )
    except Exception as e:
        # Don't let a failed soft-delete bury the success event; the
        # user can still trigger the standalone Delete action.
        logger.error(
            f"Auto-soft-delete failed for deployment {task.deploymentId}: {e}"
        )


def _notify_deploy_succeeded(db: Session, task, outputs: Any) -> None:
    """Send the success notification mail for a completed deploy.

    Reuses the ``outputs`` dict pulled in the task-succeeded branch.
    The notifier handles its own errors so a flaky SMTP never tanks
    the deploy.
    """
    try:
        deployment_notifier.notify_deployment_succeeded(
            db,
            task.deploymentId,
            terraform_outputs=outputs if isinstance(outputs, dict) else None,
        )
    except Exception as e:
        logger.warning(
            f"Deployment notify failed for {task.deploymentId}: {e}"
        )


def _publish_lifecycle_transition(
    task, event_type: str, failure_kind: str | None
) -> None:
    """Notify open SSE subscribers about a lifecycle transition so they
    can close their stream and trigger the static-log render.
    """
    pubsub_payload: dict[str, Any] = {
        "type": event_type,
        "deployment_id": str(task.deploymentId),
        "task_id": str(task.taskId),
        "task_type": task.type.value if task.type else None,
        "status": (
            "success" if event_type == 'task-succeeded'
            else "failed" if event_type == 'task-failed'
            else "cancelled"
        ),
    }
    # Attach ``failure_kind`` only on task-failed and only when
    # classified; frontends treat missing/None as a worker failure.
    if event_type == 'task-failed' and failure_kind:
        pubsub_payload["failure_kind"] = failure_kind
    pubsub.publish(str(task.deploymentId), pubsub_payload)


def _handle_lifecycle_event(event: dict, event_type: str, celery_task_id: str) -> None:
    """Process a lifecycle event: update the task row + side-effects.

    Looks up the task by ``celery_task_id``, dispatches to the per-event
    builder for the update payload, then applies the shared side-effects
    (DB update, auto-soft-delete, deploy notify, pubsub).
    """
    db: Session = SessionLocal()
    try:
        # Find task by celery_task_id
        tasks = crud_tasks.get_tasks(db, celery_task_id=celery_task_id)
        if not tasks:
            logger.warning(f"Task not found for celery_task_id: {celery_task_id}")
            return

        task = tasks[0]
        update_data: dict = {}
        # Pre-initialise so the notify hook can read it regardless of
        # branch; the task-succeeded branch overwrites it.
        outputs: Any = None
        # Classification of a task-failed event, carried through to the
        # SSE pubsub event:
        #   * ``worker_failure`` — worker raised a structured ``Failure``.
        #   * ``celery_infrastructure`` — a Celery/broker-level issue
        #     where the deployment itself wasn't touched.
        failure_kind: str | None = None

        # Handle different event types
        if event_type == 'task-started':
            update_data = _handle_task_started(celery_task_id)
        elif event_type == 'task-succeeded':
            update_data, outputs = _handle_task_succeeded(celery_task_id)
        elif event_type == 'task-failed':
            update_data, failure_kind = _handle_task_failed(celery_task_id, event)
        elif event_type == 'task-revoked':
            update_data = _handle_task_revoked(celery_task_id)

        # Update task in database
        if update_data:
            crud_tasks.update_task(db, task.taskId, update_data)
            logger.info(f"Updated task {task.taskId} from event {event_type}")

        if event_type == 'task-succeeded' and task.type == TaskType.DESTROY:
            _auto_soft_delete_on_destroy(db, task)

        if event_type == 'task-succeeded' and task.type == TaskType.DEPLOY:
            _notify_deploy_succeeded(db, task, outputs)

        if event_type in ('task-succeeded', 'task-failed', 'task-revoked'):
            _publish_lifecycle_transition(task, event_type, failure_kind)

    except Exception as e:
        logger.error(f"Error processing event {event_type} for task {celery_task_id}: {e}")

    finally:
        db.close()


# Backoff between reconnect attempts, in seconds. A connection that held for at
# least ``_RECONNECT_MAX_DELAY`` counts as healthy and resets the delay.
_RECONNECT_MIN_DELAY = 1.0
_RECONNECT_MAX_DELAY = 60.0


def _handle_event(event: dict) -> None:
    """Process one incoming Celery event."""
    event_type = event.get('type')
    celery_task_id = event.get('uuid')

    # ----- Custom events from the worker (live progress/logs) -----
    if event_type in ('task-progress', 'task-log'):
        _handle_custom_event(event)
        return

    if not celery_task_id:
        return

    _handle_lifecycle_event(event, event_type, celery_task_id)


def _listen_once() -> None:
    """Hold one broker connection and process events until it ends.

    ``capture`` blocks for as long as the connection lives, so this returns
    (or raises) only when the connection is gone.
    """
    with celery_app.connection() as connection:
        recv = EventReceiver(
            connection,
            handlers={
                'task-started': _handle_event,
                'task-succeeded': _handle_event,
                'task-failed': _handle_event,
                'task-revoked': _handle_event,
                # Custom events emitted by the worker for live progress
                # and per-line log tail. Routed to the same handler;
                # branched at the top.
                'task-progress': _handle_event,
                'task-log': _handle_event,
            }
        )

        logger.info("Celery event listener ready, waiting for events...")
        recv.capture(limit=None, timeout=None, wakeup=True)


def start_event_listener() -> None:
    """Listen to Celery events from RabbitMQ, reconnecting when the link drops.

    This runs in a background thread and never returns. It used to open the
    connection once; when RabbitMQ restarted or the network blinked, the thread
    ended with an exception nobody saw and the backend received no task events
    until it was restarted itself.
    """
    logger.info("Starting Celery event listener...")
    delay = _RECONNECT_MIN_DELAY
    while True:
        started = time.monotonic()
        failure: Exception | None = None
        try:
            _listen_once()
        except Exception as exc:
            failure = exc
        if time.monotonic() - started >= _RECONNECT_MAX_DELAY:
            delay = _RECONNECT_MIN_DELAY
        if failure is None:
            logger.warning("Celery event listener stopped; reconnecting in %.0fs", delay)
        else:
            logger.error(
                "Celery event listener lost its connection; reconnecting in %.0fs",
                delay,
                exc_info=failure,
            )
        time.sleep(delay)
        delay = min(delay * 2, _RECONNECT_MAX_DELAY)


if __name__ == "__main__":
    start_event_listener()
