"""lti context memberships url

Revision ID: ea769204620c
Revises: b988e7ef2934
Create Date: 2026-09-19 17:55:43.215934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea769204620c'
down_revision: Union[str, None] = 'b988e7ef2934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lti_contexts', sa.Column('memberships_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lti_contexts', 'memberships_url')
    # ### end Alembic commands ###
